"""updated email and phone type

Revision ID: 04f3f755fbb4
Revises: fa6229d2f0b1
Create Date: 2025-01-13 10:02:37.515589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f3f755fbb4'
down_revision = 'fa6229d2f0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('admins_email_key', type_='unique')
        batch_op.drop_constraint('admins_phone_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint('admins_phone_number_key', ['phone_number'])
        batch_op.create_unique_constraint('admins_email_key', ['email'])

    # ### end Alembic commands ###
