"""updated fields of admin

Revision ID: d2c3e1745673
Revises: 0ac2d85c5c58
Create Date: 2025-01-12 22:03:55.043029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c3e1745673'
down_revision = '0ac2d85c5c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('admin_password', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('admins_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['admin_name'])
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('admins_username_key', ['username'])
        batch_op.drop_column('admin_password')
        batch_op.drop_column('admin_name')

    # ### end Alembic commands ###
